library("phytools")
a<-read.tree("mapnh_240.nwk")
b<-read.table("mapnh_240.ratio.2.final",row.names=1)
b$gcstar<-b$V4/(b$V2+b$V4)
gc1<-setNames(b$gcstar,rownames(b))
gc.contMap<-contMap(a,gc1,plot=FALSE,res=400)
pdf("GC*_COA1.pdf",width=100,height=200)
plot(gc.contMap,fsize=c(4.5,5),leg.txt="GC* COA1",lwd=6)
dev.off()

